### ISSUE TITLE
Unable to run commands via exec/execSync

### ISSUE THREAD

**Issue by Teomayo** [fauna-labs/fauna-schema-migrate#59]
I’m not sure if this is intended or not, but it seemed viable to do give the fact its possible to set the `FAUNA_ADMIN_KEY ` environment variable I thought it could be a quick approach to apply changes to multiple databases. For testing purposes the code would look something like the following:

```
process.env['FAUNA_ADMIN_KEY'] = secret_key;
var parentClient = new faunadb.Client({secret: secret_key});


async function runCmd(cmd) {
    try {
        const output = execSync(cmd, { encoding: 'utf-8' })
        console.log('Output was:\n', output);
    } catch (error) {
        console.log(error)
    }
}
  
async function apply_migration(client) {

    let child_databases = await client.query(q.Paginate(q.Databases()));
    var child_databases_list = [];
    child_databases.data.forEach(async (value, index, array) => {
        var child_db_name = `${value.id}`;
        child_databases_list.push(child_db_name);
    });
    console.log(list)
    for (i=0; i < list.length; i++) {
        let cmdString =  `npx fauna-schema-migrate apply ${i+1} ${list[i]}`
        console.log(cmdString)
        await runcmd(cmdString)
        }

    return true
}  

apply_migration(parentClient)
.then((ret) => console.log(ret))
```

The `cmdString` variable uses the syntax noted in the [README](https://github.com/fauna-labs/fauna-schema-migrate#extras) to be able to apply changes to a child database. This will return the following output:
![image](https://user-images.githubusercontent.com/40042660/119665770-b58c1280-be02-11eb-9f00-e5b891ac6732.png)

Based on this, I followed the link and thought I could fix this by setting `process.stdin.setRawMode(false)` at the top of the script, but this did not work either. On the Fauna end, the **migrations** collection gets created in each database but no document is created within it and no other collections/indexes/functions are created either. 

Is there a more accepted way to be able to some kind of application this way? 
FYI: this error occurs if I just use `apply` and set the `FAUNA_ADMIN_KEY` but the migration goes through, it only doesn't go through when using the following notation: `fauna-schema-migrate apply 1 nameOfChildDb1`

**Comment by fauna-brecht** [comment]
Try setting --legacy as an option in the ```npx fauna-schema-migrate apply ${i+1} ${list[i]}``` command. This is caused by ink, legacy mode prints plain text without using ink. 

I'm not entirely sure but I think that you are trying to use ```fauna-schema-migrate apply 1 nameOfChildDb1``` in a wrong way. If you use that, you are expected to write your resources in child folders as explained in the README (look for "Managing multiple databases"). Or look at the [tests ](https://github.com/fauna-labs/fauna-schema-migrate/tree/main/tests/multi_db)to learn more if you want to go that route. Your approach with exec should work fine though. 

PS: currently childdb tests are disabled since sometimes they fail. That is probably due to [this ](https://github.com/fauna-labs/fauna-schema-migrate/issues/24)issue.

**Comment by Teomayo** [comment]
The --legacy flag has removed the plain text print and yes it does look like I was using it the wrong way, I read that section more closely and the script is working fine now. Thanks for the quick reply!
